quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/searchpe_db
      additional-jdbc-properties:
        reWriteBatchedInserts: "true"
    password: searchpe_password
    username: searchpe_username

  hibernate-orm:
    database:
      generation: none
    sql-load-script: no-file
    log:
      sql: false
    jdbc:
      statement-batch-size: 5000

  quartz:
    clustered: true
    store-type: JDBC_CMT

  flyway:
    migrate-at-start: true
    connect-retries: 3

  hibernate-search-orm:
    elasticsearch:
      username: es_username
      password: es_password
      hosts: localhost:9200
      protocol: HTTP
      version: 7
      analysis:
        configurer: bean:searchpeAnalysisConfigurer
    schema-management:
      strategy: CREATE_OR_VALIDATE
    automatic-indexing:
      synchronization:
        strategy: write-sync

searchpe:
  sunat:
    padronReducidoUrl: http://www2.sunat.gob.pe/padron_reducido_ruc.zip
    filter:
      - ACTIVO
  workspace:
    directory: searchpe/workspace
    connectionTimeout: 100000
    readTimeout: 100000
  scheduled:
    cron: "0 0 1 * * ?"

"%dev":
  quarkus:
    hibernate-search-orm:
      automatic-indexing:
        synchronization:
          strategy: sync
  searchpe:
    sunat:
      padronReducidoUrl: https://raw.githubusercontent.com/project-openubl/searchpe/master/padron_reducido_ruc.zip

"%test":
  quarkus:
    hibernate-search-orm:
      automatic-indexing:
        synchronization:
          strategy: sync
  searchpe:
    sunat:
      padronReducidoUrl: https://raw.githubusercontent.com/project-openubl/searchpe/master/padron_reducido_ruc.zip

"%prod-gh":
  quarkus:
    hibernate-search-orm:
      automatic-indexing:
        synchronization:
          strategy: sync
  searchpe:
    sunat:
      padronReducidoUrl: https://raw.githubusercontent.com/project-openubl/searchpe/master/padron_reducido_ruc.zip
