quarkus:
  quartz:
    clustered: true
    store-type: JDBC_CMT

  # Datasource configuration.
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/searchpe_db
      additional-jdbc-properties:
        reWriteBatchedInserts: "true"
    password: searchpe_password
    username: searchpe_username

# Hibernate configuration
  hibernate-orm:
    database:
      generation: none
    log:
      sql: false
    sql-load-script: no-file
    jdbc:
      statement-batch-size: 2000

# Flyway
  flyway:
    connect-retries: 10
    table: flyway_quarkus_history
    migrate-at-start: true
    baseline-on-migrate: true
    baseline-version: "1.0"
    baseline-description: Flyway

searchpe:
  sunat:
    padronReducidoUrl: http://www2.sunat.gob.pe/padron_reducido_ruc.zip
  workspace:
    directory: searchpeWorkspace
    connectionTimeout: 100000
    readTimeout: 100000
  scheduled:
    cron: "0 0 1 * * ?"

"%dev":
  searchpe:
    sunat:
      padronReducidoUrl: https://raw.githubusercontent.com/project-openubl/searchpe/master/padron_reducido_ruc.zip

"%test":
  searchpe:
    sunat:
      padronReducidoUrl: https://raw.githubusercontent.com/project-openubl/searchpe/master/padron_reducido_ruc.zip

"%prod-gh":
  searchpe:
    sunat:
      padronReducidoUrl: https://raw.githubusercontent.com/project-openubl/searchpe/master/padron_reducido_ruc.zip
