quarkus:
#  datasource:
#    db-kind: h2
#    jdbc:
#      url: jdbc:h2:./searchpe/h2/data/searchpe
#    password: sa
#    username: sa
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/searchpe_db
      additional-jdbc-properties:
        reWriteBatchedInserts: "true"
    password: searchpe_password
    username: searchpe_username

  hibernate-orm:
    database:
      generation: validate
    sql-load-script: no-file
    log:
      sql: false
    jdbc:
      statement-batch-size: 2000

  quartz:
    clustered: true
    store-type: JDBC_CMT

  flyway:
    migrate-at-start: true
    connect-retries: 10

searchpe:
  sunat:
    padronReducidoUrl: http://www2.sunat.gob.pe/padron_reducido_ruc.zip
  workspace:
    directory: searchpe/workspace
    connectionTimeout: 100000
    readTimeout: 100000
  scheduled:
    cron: "0 0 1 * * ?"

"%dev":
  searchpe:
    sunat:
      padronReducidoUrl: https://raw.githubusercontent.com/project-openubl/searchpe/master/padron_reducido_ruc.zip

"%test":
  searchpe:
    sunat:
      padronReducidoUrl: https://raw.githubusercontent.com/project-openubl/searchpe/master/padron_reducido_ruc.zip

"%prod-gh":
  searchpe:
    sunat:
      padronReducidoUrl: https://raw.githubusercontent.com/project-openubl/searchpe/master/padron_reducido_ruc.zip
